### ISSUE TITLE
Mocking urls with query params doesn´t work

### ISSUE THREAD

**Issue by albelop** [BeTheWeb/mockme#59]
When trying to mock a URL that includes query params, no mock is returned, because the matching with the query object is done in a strict way (deep equal). 

Also, the response function defined in the the mock is not receiving the query as function parameter.

**Comment by jdevega** [comment]
@albelop we have an ongoing branch where this is being tackled. We are planning to merge it ASAP so you can try it and tell us if it's already fixed.
